CHANGELOG.md, ci.cd/Makefile, cumulus_lambda_functions/cumulus_stac/collection_transformer.py, cumulus_lambda_functions/cumulus_stac/item_transformer.py, cumulus_lambda_functions/cumulus_stac/stac_transformer_abstract.py, cumulus_lambda_functions/lib/time_utils.py, setup.py, tests/cumulus_lambda_functions/cumulus_stac/test_collection_transformer.py, tests/cumulus_lambda_functions/cumulus_stac/test_item_transformer.py
=> feat: added Updated time in collection & item STAC dictionaries

CHANGELOG.md, cumulus_lambda_functions/stage_in_out/download_granules_daac.py, cumulus_lambda_functions/stage_in_out/download_granules_s3.py, setup.py, tests/integration_tests/test_docker_entry.py
=> fix: downloaded stac to return local absolute path

CHANGELOG.md, cumulus_lambda_functions/lib/earthdata_login/urs_token.py, cumulus_lambda_functions/stage_in_out/download_granules_abstract.py, cumulus_lambda_functions/stage_in_out/download_granules_daac.py, docker/stage-in-stage-out/dc-002-download.yaml, setup.py, tests/cumulus_lambda_functions/lib/earthdata_login/test_urs_token_retriever.py, tests/integration_tests/test_docker_entry.py
=> fix: download error

ci.cd/update_version_commit.sh
=> chore: update version + change log

ci.cd/update_version_commit.sh
- [ADD] ...
- [CHANGE] ...
- [FIX] ...
=> fix: version PR not creating

ci.cd/update_version_commit.sh
- [ADD] ...
- [CHANGE] ...
- [FIX] ...
=> fix: PR creation failed

ci.cd/update_version_commit.sh
- [ADD] ...
- [CHANGE] ...
- [FIX] ...
=> fix: still PR issue

ci.cd/update_version_commit.sh
- [ADD] ...
- [CHANGE] ...
- [FIX] ...
=> fix: still PR issue. did see some errors

cumulus_lambda_functions/stage_in_out/catalog_granules_unity.py, cumulus_lambda_functions/uds_api/collections_api.py, tests/cumulus_lambda_functions/uds_api/test_uds_api.py, tests/integration_tests/test_admin_crud.py
=> feat: Collection validation in catalog

cumulus_lambda_functions/uds_api/collections_api.py, tests/cumulus_lambda_functions/uds_api/test_uds_api.py, tests/integration_tests/test_admin_crud.py, tf-module/unity-cumulus/main.tf, tf-module/unity-cumulus/variables.tf
=> fix: Metadata stac generate cmr  file postfix

.github/workflows/pr_merge.yml, ci.cd/update_version_commit.sh
- [ADD] ...
- [CHANGE] ...
- [FIX] ...
=> fix: No double version update pr

.github/workflows/pr_merge.yml, ci.cd/update_version_commit.sh
- [ADD] ...
- [CHANGE] ...
- [FIX] ...
=> fix: No double version update pr 2

.github/workflows/pr_merge.yml, ci.cd/update_version_commit.sh
- [ADD] ...
- [CHANGE] ...
- [FIX] ...
=> fix: No double version update pr 3

cumulus_lambda_functions/granules_to_es/granules_index_mapping.py, cumulus_lambda_functions/granules_to_es/granules_indexer.py, tests/integration_tests/test_custom_metadata_end_to_end.py, tests/integration_tests/test_old_datatype_end_to_end.py
=> fix: Granules CNM bug fixes

cumulus_lambda_functions/cumulus_stac/collection_transformer.py, cumulus_lambda_functions/uds_api/catalog_api.py, cumulus_lambda_functions/uds_api/collections_api.py, cumulus_lambda_functions/uds_api/dapa/granules_dapa_query_es.py, cumulus_lambda_functions/uds_api/fast_api_utils.py, cumulus_lambda_functions/uds_api/granules_api.py, cumulus_lambda_functions/uds_api/web_service.py, tests/integration_tests/test_uds_api.py
- Added a single granule endpoint
- Added parent link
- Added self link
=> fix: add cors to FAST API

tf-module/unity-cumulus/main.tf, tf-module/unity-cumulus/variables.tf
Closes #351 
Dependency for https://github.jpl.nasa.gov/unity-uds/cumulus-template-deploy/pull/10
=> feat: Add Health check SSM

cumulus_lambda_functions/stage_in_out/upload_granules_by_complete_catalog_s3.py, docker/stage-in-stage-out/dc-003-upload.yaml, tests/integration_tests/test_docker_stage_out.py
Closes #356
- optional environment variable the folder in S3 to upload (defaulted to `stage_out`)
- readable time including millisecond for uniqueness (example: stage_out/successful_features_2024-04-11T21:29:47.095564.json)
=> feat: uploading successful feature collection to s3

cumulus_lambda_functions/uds_api/fast_api_utils.py, cumulus_lambda_functions/uds_api/web_service.py, cumulus_lambda_functions/uds_api/web_service_stac_browser.py, docker/docker-compose-web-service.yml
=> feat: Different web service for STAC browser

requirements.txt
=> feat: bump uds-lib version

tf-module/unity-cumulus/main.tf
=> fix: Healthcheck update

cumulus_lambda_functions/lib/uds_db/uds_collections.py, requirements.txt
=> fix: case insensitive

tf-module/unity-cumulus/granules_cnm_ingester.tf
=> Increased memory_size for granules_cnm_ingester to 512.

requirements.txt
Closes https://github.com/unity-sds/unity-data-services/issues/574
=> fix: lib version bump
